name: test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  provider: ^6.0.5
  image_picker: ^0.8.4+5
  firebase_storage: ^11.7.6
  shared_preferences: ^2.1.1
  firebase_messaging: ^14.9.3
  flutter_svg: ^1.0.2
  intl: ^0.19.0
  awesome_notifications: ^0.0.6+12

  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/icons/ring.svg
    # - assets/icons/bracelet.svg
    # - assets/icons/necklace.svg
    # - assets/icons/earrings.svg
